chat/urls.py
# chat/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.chat_view, name='chat'),
]

helpdesk/urls.py
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('tickets/', include('tickets.urls')),
    path('chat/', include('chat.urls')),

]

tickets/urls.py
# tickets/urls.py

from django.urls import path
from .views import TicketListView, CreateTicketView, TicketDetailView, TicketUpdateView, TicketDeleteView, \
    TakeTicketView, DoneTicketView

urlpatterns = [
    path('', TicketListView.as_view(), name='inbox'),
    path('create/', CreateTicketView.as_view(), name='create_ticket'),
    path('ticket/<int:pk>/', TicketDetailView.as_view(), name='ticket_detail'),
    path('ticket/<int:pk>/edit/', TicketUpdateView.as_view(), name='ticket_update'),
    path('ticket/<int:pk>/delete/', TicketDeleteView.as_view(), name='ticket_delete'),
    path('ticket/<int:pk>/take/', TakeTicketView.as_view(), name='take_ticket'),
    path('ticket/<int:pk>/done/', DoneTicketView.as_view(), name='done_ticket'),
]

tickets/models.py
# tickets/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Ticket(models.Model):
    URGENCY_CHOICES = [
        ('Low', 'Низкая'),
        ('Medium', 'Средняя'),
        ('High', 'Высокая'),
    ]

    STATUS_CHOICES = [
        ('New', 'Новая'),
        ('In process', 'В процессе'),
        ('Done', 'Завершена'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    responsible = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True,
                                    related_name='responsible_tickets')
    subject = models.CharField(max_length=100)
    description = models.TextField()
    urgent = models.CharField(max_length=6, choices=URGENCY_CHOICES)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='New')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.subject

    def get_urgent_display(self):
        return dict(self.URGENCY_CHOICES).get(self.urgent, self.urgent)

    def get_status_display(self):
        return dict(self.STATUS_CHOICES).get(self.status, self.status)

tickets/forms.py
# tickets/forms.py
from django import forms
from .models import Ticket


class TicketForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = ('subject', 'description', 'urgent')
        labels = {
            'subject': 'Тема заявки',
            'description': 'Описание заявки',
            'urgent': 'Срочность'
        }
        widgets = {
            'subject': forms.TextInput(attrs={
                'class': 'appearance-none border rounded-lg bg-zinc-300 w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline'}),
            'description': forms.Textarea(attrs={
                'rows': 5,
                'cols': 40,
                'class': 'appearance-none border rounded-lg bg-zinc-300 w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline'
            }),
            'urgent': forms.Select(attrs={
                'class': 'appearance-none border rounded-lg bg-zinc-300 w-full py-2 px-3 leading-tight focus:outline-none focus:shadow-outline '}),

        }

tickets/views.py
# tickets/views.py

from django.urls import reverse
from django.shortcuts import redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from django.views import View
from .models import Ticket
from .forms import TicketForm


class CreateTicketView(CreateView):
    model = Ticket
    form_class = TicketForm
    template_name = 'tickets/create_ticket.html'
    success_url = reverse_lazy('inbox')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return self.success_url


class TicketListView(LoginRequiredMixin, ListView):
    model = Ticket
    template_name = 'tickets/tickets.html'
    context_object_name = 'tickets'

    def get_queryset(self):
        user = self.request.user
        if user.is_staff:
            return Ticket.objects.all()  # Для сотрудников
        else:
            return Ticket.objects.filter(user=user)  # Для обычных пользователей


class TicketDetailView(LoginRequiredMixin, DetailView):
    model = Ticket
    template_name = 'tickets/ticket_detail.html'
    context_object_name = 'ticket'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_staff'] = self.request.user.is_staff
        return context


class TakeTicketView(LoginRequiredMixin, View):
    def post(self, request, pk):
        ticket = get_object_or_404(Ticket, pk=pk)
        ticket.responsible = request.user
        ticket.status = 'In process'
        ticket.save()
        return redirect('ticket_detail', pk=ticket.pk)


class DoneTicketView(LoginRequiredMixin, View):
    def post(self, request, pk):
        ticket = get_object_or_404(Ticket, pk=pk)
        ticket.responsible = request.user
        ticket.status = 'Done'
        ticket.save()
        return redirect('ticket_detail', pk=ticket.pk)


class TicketUpdateView(LoginRequiredMixin, UpdateView):
    model = Ticket
    form_class = TicketForm
    template_name = 'tickets/ticket_form.html'

    def get_success_url(self):
        return reverse('ticket_detail', kwargs={'pk': self.object.pk})


class TicketDeleteView(LoginRequiredMixin, DeleteView):
    model = Ticket
    template_name = 'tickets/ticket_confirm_delete.html'
    success_url = reverse_lazy('inbox')

tickets/templates/tickets/create_ticket.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Создать заявку{% endblock %}

{% block content %}
    <div class="container mx-auto p-10">
        <form method="post" class="w-full max-w-md mx-auto bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
          {% csrf_token %}
          <div class="mb-4">
            <img class="mx-auto pb-8" src="{% static 'images/sibintek.svg' %}" alt="Сибинтек">
            <label class="block text-gray-700 font-bold mb-2" for="id_subject">{{ form.subject.label }}</label>
            {{ form.subject }}
          </div>
          <div class="mb-4">
            <label class="block text-gray-700 font-bold mb-2" for="id_description">{{ form.description.label }}</label>
            {{ form.description }}
          </div>
          <div class="mb-6">
            <label class="block text-gray-700 font-bold mb-2" for="id_urgent">{{ form.urgent.label }}</label>
            {{ form.urgent }}
          </div>
          <div class="flex items-center justify-between">
            <button class="bg-yellow-400 mx-auto hover:bg-yellow-500 text-gray-700 font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
              Отправить заявку
            </button>
          </div>
        </form>
    </div>
{% endblock %}

tickets/templates/tickets/ticket_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <div class="max-w-4xl mx-auto py-10">
    <h1 class="text-2xl font-bold mb-4">Удалить заявку</h1>
    <div class="bg-white shadow-md rounded-lg p-6">
      <p class="text-gray-700 mb-4">Вы уверены, что хотите удалить заявку "<strong>{{ object.subject }}</strong>"?</p>
      <form method="post">
        {% csrf_token %}
        <button type="submit" class="bg-red-500 text-white px-4 py-2 rounded hover:bg-red-700">Удалить</button>
        <a href="{% url 'ticket_detail' object.id %}" class="bg-gray-500 text-white px-4 py-2 rounded hover:bg-gray-700">Отмена</a>
      </form>
    </div>
  </div>
{% endblock %}

tickets/templates/tickets/ticket_detail.html
{% extends 'base.html' %}

{% block content %}
  <div class="max-w-4xl mx-auto py-10">
    <h1 class="text-2xl font-bold mb-4">Детали заявки</h1>
    <div class="bg-white shadow-md rounded-lg p-6">
      <div class="mb-4">
        <label class="block text-gray-700 font-bold mb-2">ID:</label>
        <p class="text-gray-900">{{ ticket.id }}</p>
      </div>
      <div class="mb-4">
        <label class="block text-gray-700 font-bold mb-2">Тема:</label>
        <p class="text-gray-900">{{ ticket.subject }}</p>
      </div>
      <div class="mb-4">
        <label class="block text-gray-700 font-bold mb-2">Описание:</label>
        <p class="text-gray-900">{{ ticket.description }}</p>
      </div>
      <div class="mb-4">
        <label class="block text-gray-700 font-bold mb-2">Срочность:</label>
        <p class="text-gray-900">{{ ticket.get_urgent_display }}</p>
      </div>
      <div class="mb-4">
        <label class="block text-gray-700 font-bold mb-2">Статус:</label>
        <p class="text-gray-900">{{ ticket.get_status_display }}</p>
      </div>
      <div class="mb-4">
        <label class="block text-gray-700 font-bold mb-2">Дата создания:</label>
        <p class="text-gray-900">{{ ticket.created_at }}</p>
      </div>
      <div class="mb-4">
        <label class="block text-gray-700 font-bold mb-2">Ответственный:</label>
        <p class="text-gray-900">
          {% if ticket.responsible %}
            {{ ticket.responsible }}
          {% else %}
            Отсутствует
          {% endif %}
        </p>
      </div>
      <div class="flex space-x-4">
        {% if is_staff and not ticket.responsible %}
            <form action="{% url 'take_ticket' ticket.pk %}" method="post">
              {% csrf_token %}
              <button type="submit" class="bg-yellow-500 text-white px-4 py-2 rounded hover:bg-yellow-700">Взять заявку</button>
            </form>
        {% endif %}
        {% if is_staff and ticket.responsible and not ticket.status == 'Done'%}
            <form action="{% url 'done_ticket' ticket.pk %}" method="post">
              {% csrf_token %}
              <button type="submit" class="bg-green-500 text-white px-4 py-2 rounded hover:bg-green-700">Заявка выполнена</button>
            </form>
        {% endif %}
        <a href="{% url 'ticket_update' ticket.id %}" class="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-700">Редактировать</a>
        <a href="{% url 'ticket_delete' ticket.id %}" class="bg-red-500 text-white px-4 py-2 rounded hover:bg-red-700">Удалить</a>
      </div>
    </div>
  </div>
{% endblock %}

tickets/templates/tickets/ticket_form.html
{% extends 'base.html' %}

{% block content %}
  <div class="max-w-4xl mx-auto py-10">
    <h1 class="text-2xl font-bold mb-4">Редактировать заявку</h1>
    <div class="bg-white shadow-md rounded-lg p-6">
      <form method="post" class="space-y-4">
        {% csrf_token %}
        <div>
          <label for="subject" class="block text-gray-700 font-bold mb-2">Тема заявки</label>
          {{ form.subject }}
        </div>
        <div>
          <label for="description" class="block text-gray-700 font-bold mb-2">Описание заявки</label>
          {{ form.description }}
        </div>
        <div>
          <label for="urgent" class="block text-gray-700 font-bold mb-2">Срочность</label>
          {{ form.urgent }}
        </div>
        <div>
          <button type="submit" class="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-700">Сохранить</button>
        </div>
      </form>
    </div>
  </div>
{% endblock %}

tickets/templates/tickets/tickets.html
<!-- tickets/tickets.html -->
{% extends 'base.html' %}
{% load static %}

{% block title %}Clients{% endblock %}

{% block content %}
    <h1 class="text-2xl font-bold m-4">Список заявок</h1>

    <div class="overflow-x-auto px-7">
        <table class="mx-auto min-w-full rounded-lg overflow-hidden">
            <thead class="bg-yellow-400">
                <tr class="divide-x divide-gray-500">
                    <th class="table-header">ID</th>
                    <th class="table-header">Тема заявки</th>
                    <th class="table-header">ФИО</th>
                    <th class="table-header">Статус</th>
                    <th class="table-header">Дата создания</th>
                    <th class="table-header">Срочность</th>
                    <th class="table-header">Ответственный</th>
                </tr>
            </thead>
            <tbody class="bg-white divide-y divide-gray-300 text-center">
                {% for ticket in tickets %}
                    <tr class="divide-x divide-gray-200">
                        <td class="table-cell text-center">{{ ticket.id }}</td>
                        <td class="table-cell underline underline-offset-5 decoration-yellow-400">
                            <a href="{% url 'ticket_detail' ticket.id %}">{{ ticket.subject }}</a>
                        </td>
                        <td class="table-cell">
                            <a href="{% url 'profile_detail' ticket.user.id %}">{{ ticket.user }}</a>
                        </td>
                        <td class="table-cell">{{ ticket.get_status_display }}</td>
                        <td class="table-cell">{{ ticket.created_at }}</td>
                        <td class="table-cell">{{ ticket.get_urgent_display }}</td>
                        <td class="table-cell">
                            {% if ticket.responsible %}
                                <a href="{% url 'profile_detail' ticket.responsible.id %}">{{ ticket.responsible }}</a>
                            {% else %}
                                Отсутствует
                            {% endif %}
                        </td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="7" class="text-center">Нет заявок</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}